server:
  port: 8081
spring:
  application:
    name: drone-data-management
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/drone-data
    username: root
    password: 1230000
  jackson:
    default-property-inclusion: non_null # JSON?????????
  data:
    redis:
      host: 124.71.162.119
      port: 6379
      password:
      lettuce:
        pool:
          max-active: 20
          max-idle: 10
          min-idle: 5
          test-while-idle: true
          time-between-eviction-runs: 30s
          shutdown-timeout: 5000ms
